### ISSUE TITLE
Spike: Investigate Azure's API Capabilities for data tracking

### ISSUE THREAD

**Issue by sah7829** [The-Spooky-Frogs/LenelS2Dashboard#14]
# Investigate Azure's API Capabilities for data tracking

## Problem Statement

As we begin to decide on scope and solutions, since Elements is our initial scope our main focus should be on Azure. Understand how Azure sends data for tracking their metrics around cost, performance, and any other KPIs including security

## Goal

What do you want to achieve with this spike? What are you hoping to learn or prove?

## Hypothesis

What is your best guess about how to solve the problem or answer the question? What assumptions are you making?

## Questions

List the specific questions you need to answer to achieve your goal. These should be small, manageable questions that will help you make progress.

- [ ] What KPIs can be exported from Azure? Are there any?
- [ ] How are these exported from Azure? What tools might we need to use for it?
- [ ] Are there any costs associated with this approach?

## Research Tasks

List the specific tasks you need to perform to answer the questions and achieve your goal. These should be small, manageable tasks that will help you make progress.

- [ ] [Task 1]
- [ ] [Task 2]
- [ ] [Task 3]

## Results and Conclusion

Summarize the results of your research. What did you learn? What worked? What didn't work? What are the implications of the results?

Based on your results, what is your conclusion? What do you recommend? What is your next step?
